name: talk_to_me
description: A sample web application built using AngularDart
dependencies:
  browser: ">=0.8.10"
  angular: "0.9.10"
  uuid: ">=0.1.6 <=1.0.0"
  unittest: ">= 0.8.10 <2.0.0" #has to be here because of the issue with route_hierarchical
dev_dependencies:
  dartmocks: ">= 0.5.0"
environment:
  sdk: ">=0.8.10 <2.0.0"