name: TalkToMe
description: A server-less Web application built using AngularDart and WebRTC
dependencies:
  browser: ">=0.8.10"
  angular: ">=0.9.0 <2.0.0"
  uuid: ">=0.1.6 <=1.0.0"
environment:
  sdk: ">=0.8.10 <2.0.0"